### ISSUE TITLE
Crosswalk ECS example in docs is not working

### ISSUE THREAD

**Issue by gthuang** [pulumi/pulumi-hugo#2278]
### What happened?

The Python example for this [crosswalk load balanced ecs service](https://www.pulumi.com/docs/guides/crosswalk/aws/ecs/#creating-a-load-balanced-ecs-service) does not work.

### Steps to reproduce

Running `pulumi up` on this code:
```
import pulumi
import pulumi_aws as aws
import pulumi_awsx as awsx

cluster = aws.ecs.Cluster("default-cluster")

lb = awsx.lb.ApplicationLoadBalancer("nginx-lb")

service = awsx.ecs.FargateService("my-service",
    cluster=cluster.arn,
    desired_count=2,
    task_definition_args=awsx.ecs.FargateServiceTaskDefinitionArgs(
        container=awsx.ecs.TaskDefinitionContainerDefinitionArgs(
            image="nginx:latest",
            cpu=512,
            memory=128,
            essential=True,
            port_mappings=[awsx.ecs.TaskDefinitionPortMappingArgs(
                target_group=lb.default_target_group
            )],
        )
    )
)

pulumi.export('url', lb.load_balancer.dns_name)
```

### Expected Behavior

A successful preview of resources to update.

### Actual Behavior

```
View Live: https://app.pulumi.com/george/ecsfargate/dev/previews/b9b56d00-4e60-4bc5-af15-d6d465ccfbe5

     Type                                   Name                           Plan       Info
 +   pulumi:pulumi:Stack                    ecsfargate-dev                 create     2 errors
 +   ├─ aws:ecs:Cluster                     default-cluster                create     
 +   ├─ awsx:lb:ApplicationLoadBalancer     nginx-lb                       create     
 +   │  ├─ aws:lb:TargetGroup               nginx-lb                       create     
 +   │  ├─ aws:ec2:SecurityGroup            nginx-lb                       create     
 +   │  ├─ aws:lb:LoadBalancer              nginx-lb                       create     
 +   │  └─ aws:lb:Listener                  nginx-lb-0                     create     
 +   └─ awsx:ecs:FargateService             my-service                     create     
 +      ├─ awsx:ecs:FargateTaskDefinition   my-service                     create     
 +      │  ├─ aws:iam:Role                  my-service-task                create     
 +      │  ├─ aws:iam:Role                  my-service-execution           create     
 +      │  ├─ aws:cloudwatch:LogGroup       my-service                     create     
 +      │  ├─ aws:iam:RolePolicyAttachment  my-service-execution-9a42f520  create     
 +      │  └─ aws:ecs:TaskDefinition        my-service                     create     
 +      └─ aws:ec2:SecurityGroup            my-service-sg                  create     


Diagnostics:
  pulumi:pulumi:Stack (ecsfargate-dev):
    error: Error: The default VPC does not have any private subnets. Set `assignPublicIp` to `true`, provide `networkConfiguration`, or add private subnets to the default VPC.
        at /snapshot/awsx/bin/ecs/fargateService.js:87:23
        at /snapshot/awsx/node_modules/@pulumi/pulumi/output.js:250:35
        at Generator.next (<anonymous>)
        at /snapshot/awsx/node_modules/@pulumi/pulumi/output.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/snapshot/awsx/node_modules/@pulumi/pulumi/output.js:17:12)
        at applyHelperAsync (/snapshot/awsx/node_modules/@pulumi/pulumi/output.js:229:12)
        at /snapshot/awsx/node_modules/@pulumi/pulumi/output.js:183:65
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/Users/georgehuang/IaC/ecsfargate/venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 617, in do_rpc_call
        return monitor.RegisterResource(req)
      File "/Users/georgehuang/IaC/ecsfargate/venv/lib/python3.10/site-packages/grpc/_channel.py", line 946, in __call__
        return _end_unary_response_blocking(state, call, False, None)
      File "/Users/georgehuang/IaC/ecsfargate/venv/lib/python3.10/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
        raise _InactiveRpcError(state)
    grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
    	status = StatusCode.UNKNOWN
    	details = "The default VPC does not have any private subnets. Set `assignPublicIp` to `true`, provide `networkConfiguration`, or add private subnets to the default VPC."
    	debug_error_string = "{"created":"@1669756228.345786000","description":"Error received from peer ipv4:127.0.0.1:58925","file":"src/core/lib/surface/call.cc","file_line":967,"grpc_message":"The default VPC does not have any private subnets. Set `assignPublicIp` to `true`, provide `networkConfiguration`, or add private subnets to the default VPC.","grpc_status":2}"
    >
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/opt/homebrew/bin/pulumi-language-python-exec", line 192, in <module>
        loop.run_until_complete(coro)
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
        return future.result()
      File "/Users/georgehuang/IaC/ecsfargate/venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 126, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/georgehuang/IaC/ecsfargate/venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await wait_for_rpcs()
      File "/Users/georgehuang/IaC/ecsfargate/venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 110, in wait_for_rpcs
        raise exception
      File "/Users/georgehuang/IaC/ecsfargate/venv/lib/python3.10/site-packages/pulumi/runtime/rpc_manager.py", line 68, in rpc_wrapper
        result = await rpc
      File "/Users/georgehuang/IaC/ecsfargate/venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 622, in do_register
        resp = await asyncio.get_event_loop().run_in_executor(None, do_rpc_call)
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/Users/georgehuang/IaC/ecsfargate/venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 619, in do_rpc_call
        handle_grpc_error(exn)
      File "/Users/georgehuang/IaC/ecsfargate/venv/lib/python3.10/site-packages/pulumi/runtime/settings.py", line 273, in handle_grpc_error
        raise grpc_error_to_exception(exn)
    Exception: The default VPC does not have any private subnets. Set `assignPublicIp` to `true`, provide `networkConfiguration`, or add private subnets to the default VPC.

Outputs:
    url: output<string>

```

### Output of `pulumi about`

CLI          
Version      3.48.0
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.21.1
awsx    1.0.0
docker  3.6.1
python  unknown

Host     
OS       darwin
Version  12.5.1
Arch     arm64

This project is written in python: executable='/Users/georgehuang/iac/ecsfargate/venv/bin/python3' version='3.10.7
'

Current Stack: dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/george
User           george
Organizations  george, pulumi

Dependencies:
NAME         VERSION
pip          22.3.1
pulumi-awsx  1.0.0
setuptools   65.6.3
wheel        0.38.4

Pulumi locates its logs in /var/folders/s0/p9spf7x513gcydqylwsc8ts80000gn/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by gthuang** [comment]
was resolved here: https://github.com/pulumi/pulumi-hugo/pull/2274

**Comment by justinvp** [comment]
The fix is that `awsx.ecs.FargateService` needs `assign_public_ip=True,`, e.g.:

```python
import pulumi
import pulumi_aws as aws
import pulumi_awsx as awsx

cluster = aws.ecs.Cluster("default-cluster")

lb = awsx.lb.ApplicationLoadBalancer("nginx-lb")

service = awsx.ecs.FargateService("my-service",
    cluster=cluster.arn,
    assign_public_ip=True,
    desired_count=2,
    task_definition_args=awsx.ecs.FargateServiceTaskDefinitionArgs(
        container=awsx.ecs.TaskDefinitionContainerDefinitionArgs(
            image="nginx:latest",
            cpu=512,
            memory=128,
            essential=True,
            port_mappings=[awsx.ecs.TaskDefinitionPortMappingArgs(
                target_group=lb.default_target_group
            )],
        )
    )
)

pulumi.export('url', lb.load_balancer.dns_name)
```
